#+TITLE: pubme org mode website
#+AUTHOR: Matthew Elwin
The org-mode publishing method that I use for my website [[https://numsr.github.io]].
The goal is to enable writing class-notes websites without worrying about formatting.
This package is maintained in a good-enough-for-me state.

* Usage
1. Each website is a nested structure of =.org= mode files.
2. Running =pubme= inside this directory structure will generate an =html= directory with the website.
   #+BEGIN_folded
   =pubme= is both an emacs script file and a shell script (using emacs as the interpreter)
   #+END_folded
   - While =emacs= has the best support for =.org=, any editor can be used to write the =.org= files.
3. Files stored under =private/=  will not be published
4. See =test/= for an example of the features

There are two methods for publishing the website:
1. Setting =#+GIT-PUBLISH-URL= sets up a remote git repository. Running =pubme -p= will push the generated website to that repository.
   - This mode is most useful for publishing the website using a service other than Github Pages, but it can also be used with Github Pages.
   - In some ways this method is "cleaner" because generated files are not included in the repository itself.
2. You can add the generated output files to the git repository and publish with the Github pages feature.
   - Setup the repository on Github to use an action to publish "static html" pages and *edit* the =static.yml= file so that it publishes
     only the =html= directory.
   - Add the generated outputs to git. Doing this makes it easier to see what pages are going to be changed when you publish.
   - I recommend doing development on a separate =devel= branch and publishing pages from =main=
